name: Android CI/CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - 'gradle/**'
      - 'app/build/**'
      - 'build/**'
      - 'local.properties'
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - 'gradle/**'
      - 'app/build/**'
      - 'build/**'
      - 'local.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Chche Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Chche Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assemble
      # run: ./gradlew assembleRelease

    ## test
    - name: Test with Gradle
      run: ./gradlew test

    - name: Upload result test
      uses: actions/upload-artifact@v3
      with:
        name: test-result
        path: '**/build/reports/tests/**/*'
        if-no-files-found: warn
        retention-days: 14

    ## lint
    - name: Lint with Gradle
      run: ./gradlew lint
      continue-on-error: true

    - name: Upload result lint
      uses: actions/upload-artifact@v3
      with:
        name: lint-result
        path: '**/build/reports/lint-results-*'
        if-no-files-found: warn
        retention-days: 14

    ## ktlint
    - name: Install ktlint
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.1/ktlint
        chmod a+x ktlint
        sudo mv ktlint /usr/local/bin/

    - name: Lint with ktlint
      run: ./gradlew ktlintCheck
      continue-on-error: true

    - name: Upload result ktlint
      uses: actions/upload-artifact@v3
      with:
        name: ktlint-result
        path: '**/build/reports/ktlint/**/*'
        if-no-files-found: warn
        retention-days: 14

    ## deploy
    # https://github.com/tj-actions/changed-files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40

    # https://github.com/wzieba/Firebase-Distribution-Github-Action
    - name: Upload artifact to Firebase App Distribution (DEBUG APK)
      if: contains(steps.changed-files.outputs.all_modified_files, 'RELEASE_NOTES.md')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: developer
        releaseNotes: '(D) ${{ github.sha }}\n${{ github.event.head_commit.message }}'
        releaseNoteFile: RELEASE_NOTES.md
        file: app/build/outputs/apk/debug/app-debug.apk
      continue-on-error: true

    - name: Upload artifact to Firebase App Distribution (RELEASE APK)
      if: contains(steps.changed-files.outputs.all_modified_files, 'RELEASE_NOTES.md')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: developer
        releaseNotes: '(R) ${{ github.sha }}\n${{ github.event.head_commit.message }}'
        releaseNoteFile: RELEASE_NOTES.md
        file: app/build/outputs/apk/release/app-release-unsigned.apk
      continue-on-error: true
