name: Android CI/CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - 'gradle/**'
      - 'app/build/**'
      - 'build/**'
      - 'local.properties'
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - 'gradle/**'
      - 'app/build/**'
      - 'build/**'
      - 'local.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble

    - name: Run Tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
        continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/build/reports/tests/**/*'
        if-no-files-found: warn
        retention-days: 14

    - name: Run Lint
      uses: gradle/gradle-build-action@v2
      with:
        arguments: lint
        continue-on-error: true

    - name: Upload Lint Results
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: '**/build/reports/lint-results-*'
        if-no-files-found: warn
        retention-days: 14

    - name: Run ktlint
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlintCheck
        continue-on-error: true

    - name: Upload ktlint Results
      uses: actions/upload-artifact@v3
      with:
        name: ktlint-results
        path: '**/build/reports/ktlint/**/*'
        if-no-files-found: warn
        retention-days: 14

    - name: Run Detekt
      uses: gradle/gradle-build-action@v2
      with:
        arguments: detekt
        continue-on-error: true

    - name: Upload Detekt Results
      uses: actions/upload-artifact@v3
      with:
        name: detekt-results
        path: '**/build/reports/detekt/**/*'
        if-no-files-found: warn
        retention-days: 14

    ## deploy
    # https://github.com/tj-actions/changed-files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40

    # https://github.com/wzieba/Firebase-Distribution-Github-Action
    - name: Upload artifact to Firebase App Distribution (DEBUG APK)
      if: contains(steps.changed-files.outputs.all_modified_files, 'RELEASE_NOTES.md')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: developer
        releaseNotes: '(D) ${{ github.sha }}\n${{ github.event.head_commit.message }}'
        releaseNoteFile: RELEASE_NOTES.md
        file: app/build/outputs/apk/debug/app-debug.apk
      continue-on-error: true

    - name: Upload artifact to Firebase App Distribution (RELEASE APK)
      if: contains(steps.changed-files.outputs.all_modified_files, 'RELEASE_NOTES.md')
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: developer
        releaseNotes: '(R) ${{ github.sha }}\n${{ github.event.head_commit.message }}'
        releaseNoteFile: RELEASE_NOTES.md
        file: app/build/outputs/apk/release/app-release-unsigned.apk
      continue-on-error: true
